### ISSUE TITLE
search by isbn?

### ISSUE THREAD

**Issue by nikbucher** [jmaciasluque/hello-lucene#26]
Hi Juan

Thanks a lot for your LuceneTutorial.com page. I found a strange behaviour for the QueryParser.

Lucene version: 9.8.0

Do you know why it does lowercase a term for a StringField? Because of that I can't query by the field 'isbn':

(I added a `System.out.println("q=" + q)` before querying)

These were OK: 
- querystr: "lucene" or "Lucene", Output:
    ```
    q=title:lucene
    Found 2 hits.
    1. 193398817	Lucene in Action
    2. 55320055Z	Lucene for Dummies
    ```
- querystr: "isbn:193398817", Output: 
    ```
    q=isbn:193398817
    Found 1 hits.
    1. 193398817	Lucene in Action
    ```

But If I query for an isbn which contains a character it doesn't work:
querystr: "isbn:55320055Z", Output:
```
q=isbn:55320055z
Found 0 hits.
```

If I create a TermQuery directly using `new TermQuery(new Term("isbn", querystr))`instead, it works as expected.
querystr: "55320055Z", Output:
```
q=isbn:55320055Z
Found 1 hits.
1. 55320055Z	Lucene for Dummies
```

How can I fix that if I do **not** want to lowercase the isbn when adding the documents to index?

Thanks and best regards - Niklaus

**Comment by jmaciasluque** [comment]
You're encountering a common issue with the default behaviour of Lucene's QueryParser, which by default lowercases all terms for fields that are not explicitly configured as case-sensitive. This behaviour is intended to normalize text for most use cases where case is not significant (e.g., full-text search), but it can cause issues when searching fields where case matters, such as an ISBN field.

To prevent QueryParser from lowercasing terms for specific fields, you need to use a PerFieldAnalyzerWrapper when indexing and querying. This allows you to specify a different analyzer for the isbn field that does not lowercase terms.

```
import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.core.KeywordAnalyzer;
import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.apache.lucene.analysis.miscellaneous.PerFieldAnalyzerWrapper;
import java.util.HashMap;
import java.util.Map;

// Create a map to hold the analyzer for the isbn field
Map<String, Analyzer> analyzerPerField = new HashMap<>();
analyzerPerField.put("isbn", new KeywordAnalyzer()); // Use KeywordAnalyzer for isbn

// For all other fields, use the standard analyzer
Analyzer defaultAnalyzer = new StandardAnalyzer();
PerFieldAnalyzerWrapper wrapper = new PerFieldAnalyzerWrapper(defaultAnalyzer, analyzerPerField);

// Use this wrapper analyzer while indexing and querying
```

And then

```
// 2. query
String queryString = args.length > 0 ? args[0] : "55320055Z";

// the "title" arg specifies the default field to use
// when no field is explicitly specified in the query.
Query query = null;
try {
    // query = new QueryParser("isbn", analyzer).parse(queryString);
    query = new QueryParser("isbn", wrapper).parse(queryString);

} catch (org.apache.lucene.queryparser.classic.ParseException e) {
    e.printStackTrace();
}
```

**Comment by nikbucher** [comment]
Thanks a lot for the explanation and the sample! 🙏
